### ISSUE TITLE
out-of-bounds trees - forest polygone

### ISSUE THREAD

**Issue by aum7** [Vacuum-Tube/OSM-TPF2-Importer#11]
after successful 3rd step, i get forest outside map borders : 

![241128_trees_out_of_bounds_2](https://github.com/user-attachments/assets/fa5105ef-7ef7-4b2a-9f94-1acdbbf8fb63)

any script to disintegrate a floating forest of slovenia ? lol

thx for sharing
have fun

**Comment by Vacuum-Tube** [comment]
This is the expected behavior. The polygons can be large and are not cut to the map border.

For nodes and street segments it was easy to implement a check whether the element is outside the map. I did not implement anything for poylgon areas because I actually appreciated the forests covering the artificial map bound.

If you want, I can provide a script command that removes trees beyond the map.

**Comment by aum7** [comment]
i beg thee for the script to remove trees beyond the map, my script removed them from the map too
not that i can not add them manually

my script:
``` lua
-- Define map boundaries
local mapMinX, mapMinY = 0, 0
local mapMaxX, mapMaxY = 1024, 1024

-- Function to check if an entity's position is outside the map area
local function isOutsideMapArea(position)
    local x, y = position[1], position[2]
    return x < mapMinX or x > mapMaxX or y < mapMinY or y > mapMaxY
end

-- Fetch all ASSET_GROUP entities
for id, asset in pairs(game.interface.getEntities({radius = 1e42}, {type = "ASSET_GROUP", includeData = true})) do
    if asset.position and isOutsideMapArea(asset.position) then
        print("Removing entity with ID: " .. tostring(id)) -- Debugging line
        api.cmd.sendCommand(api.cmd.make.removeField(id))  -- Remove the entity
    end
end
```

**Comment by aum7** [comment]
the result of the above script : 

![241128 deleted trees](https://github.com/user-attachments/assets/94e5da4f-a405-4269-bd60-761aa47d1cb0)

**Comment by Vacuum-Tube** [comment]
btw: (0,0) is the center and your map seems larger than 1024

Try this

```lua
for id, asset in pairs(game.interface.getEntities({radius = 1e42}, {type = "ASSET_GROUP", includeData = true})) do
    if asset.position and not api.engine.terrain.isValidCoordinate(api.type.Vec2f.new(asset.position[1], asset.position[2])) then
        api.cmd.sendCommand(api.cmd.make.removeField(id))
    end
end
```

**Comment by aum7** [comment]
map is tiny (first steps into map-importer business, lol), the overlay is 1:50k resolution, maybe this is why it looks bigger, and it is mountainous area

quote:
"btw: (0,0) is the center" - it did crossed my mind this might be so ...

script works as expected, result:

![241129 remove assets script result](https://github.com/user-attachments/assets/6428c402-22f7-42d2-9c8e-b61d4dc9486f)

floating forest of slovenia is the thing of the past lol

thx for sharing & a prompt reply
have fun
