### ISSUE TITLE
luadata missing

### ISSUE THREAD

**Issue by Goodolandy** [Vacuum-Tube/OSM-TPF2-Importer#3]
Hello, the main.py requires import from a file called luadata but there is no mention in the documentation of the requirement for this file and where to get it.

**Comment by Vacuum-Tube** [comment]
It's a python package. They have to be installed. The requirements are listed here: https://github.com/Vacuum-Tube/OSM-TPF2-Importer/blob/main/python/requirements.txt

I will revise the docu on installation process soon (while trying to keep it simple for non-programmer users)

**Comment by Vacuum-Tube** [comment]
v1.2 is out and the installation process should be clear now. There is also an alternative without Python.
