### ISSUE TITLE
what's wrong with my code (OSM-TPF2-Importer, Method 2) 

### ISSUE THREAD

**Issue by gsh105** [Vacuum-Tube/OSM-TPF2-Importer#4]
main.exe map.osm osmdata.lua 16384,16384 39.5057951,2.5418994,2.5418994,2.5418994
Failed to execute script 'main' due to unhandled exception!

**Comment by Vacuum-Tube** [comment]
Your coordinates look a bit strange.
You have 3 times 2.5418994

The order is: `min latitude, min longitude, max latitude, max longitude`

**Comment by gsh105** [comment]
thanks creator
